# Generated by Django 5.0.1 on 2025-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12)),
                ('quotation_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('source', models.CharField(choices=[('BBG', 'Bloomberg'), ('TK', 'Thomson Reuters'), ('Reuters', 'Reuters'), ('Autre', 'Autre')], max_length=10)),
                ('entered_by', models.CharField(max_length=100)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
